CREATE TABLE public.scheduler_execution_log
(
    id               bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fire_instance_id varchar(200) NOT NULL,
    logged_at        timestamp with time zone NOT NULL,
    level            varchar(12) NOT NULL,
    log_source       varchar(80) NOT NULL,
    message          varchar(1000) NOT NULL,
    details          text,
    CONSTRAINT pk_scheduler_execution_log PRIMARY KEY (id),
    CONSTRAINT fk_scheduler_execution_log_history FOREIGN KEY (fire_instance_id)
        REFERENCES public.scheduler_execution_history (fire_instance_id) ON DELETE CASCADE,
    CONSTRAINT ck_scheduler_execution_log_level CHECK (
        level IN ('INFO', 'WARN', 'ERROR')
    )
);

CREATE INDEX idx_scheduler_execution_log_fire_instance
    ON public.scheduler_execution_log (fire_instance_id, logged_at DESC, id DESC);

INSERT INTO public.scheduler_execution_log (
    fire_instance_id, logged_at, level, log_source, message, details
)
SELECT fire_instance_id,
       COALESCE(finished_at, actual_fire_time),
       CASE
           WHEN result = 'FAILED' THEN 'ERROR'
           WHEN result = 'INTERRUPTION_REQUESTED' THEN 'WARN'
           ELSE 'INFO'
       END,
       'scheduler-history',
       message,
       NULL
FROM public.scheduler_execution_history;
