apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: observabilidade-portal
  namespace: observabilidade-portal
  labels:
    app.kubernetes.io/part-of: observabilidade-portal
spec:
  parentRefs:
    - name: wsl-gateway
      namespace: gateway-system
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/v1/auth
        - path:
            type: PathPrefix
            value: /api/v1/me
        - path:
            type: PathPrefix
            value: /api/v1/providers
        - path:
            type: PathPrefix
            value: /api/v1/authorization
        - path:
            type: PathPrefix
            value: /saml2
        - path:
            type: PathPrefix
            value: /login/saml2
      backendRefs:
        - name: identity-access-service
          port: 8083
    - matches:
        - path:
            type: PathPrefix
            value: /api/v1
      backendRefs:
        - name: scheduler-service
          port: 8081
    - backendRefs:
        - name: portal-web
          port: 3000
