apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres.yaml
  - platform-service.yaml
  - scheduler-service.yaml
  - workflow-service.yaml
  - identity-redis.yaml
  - identity-access-service.yaml
  - portal-web.yaml
  - http-route.yaml
